# Generated by Django 3.2.4 on 2021-07-10 17:56

import CRM.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('student_count', models.IntegerField()),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('status', models.CharField(default='진행중', max_length=10, null=True)),
                ('totalDatePer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('university', models.CharField(default='', max_length=50, null=True)),
                ('major', models.CharField(default='', max_length=50, null=True)),
                ('interest_language', models.CharField(default='', max_length=50, null=True)),
                ('phone_number', models.CharField(default='', max_length=100, null=True)),
                ('address', models.CharField(default='', max_length=200, null=True)),
                ('birth', models.DateField(null=True)),
                ('seat_num', models.IntegerField(null=True)),
                ('authority', models.CharField(max_length=50)),
                ('class_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.classlist')),
            ],
        ),
        migrations.CreateModel(
            name='Student_list',
            fields=[
                ('studentListNum', models.AutoField(primary_key=True, serialize=False, verbose_name=CRM.models.ClassList)),
                ('date', models.DateField(auto_now_add=True)),
                ('attendance', models.CharField(default='N', max_length=2, null=True)),
                ('absent', models.CharField(default='N', max_length=2, null=True)),
                ('late', models.CharField(default='N', max_length=2, null=True)),
                ('early', models.CharField(default='N', max_length=2, null=True)),
                ('input_time', models.DateTimeField(null=True)),
                ('output_time', models.DateTimeField(null=True)),
                ('total_time_outing', models.DateTimeField(null=True)),
                ('total_time', models.DateTimeField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.classlist')),
                ('member_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.member')),
            ],
        ),
    ]
