# Generated by Django 3.2.4 on 2021-07-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='interest_language',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='major',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='temperature',
            field=models.FloatField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='university',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_list',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student_list',
            name='inout_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student_list',
            name='output_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
