# Generated by Django 3.2.4 on 2021-07-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_list',
            name='inout_time',
        ),
        migrations.AddField(
            model_name='student_list',
            name='input_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student_list',
            name='total_time_outing',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='student_list',
            name='output_time',
            field=models.DateTimeField(null=True),
        ),
    ]
