# Generated by Django 3.2.4 on 2021-07-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20210703_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_list',
            name='absent',
            field=models.CharField(default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student_list',
            name='attendance',
            field=models.CharField(default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student_list',
            name='early',
            field=models.CharField(default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student_list',
            name='late',
            field=models.CharField(default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student_list',
            name='total_time',
            field=models.TimeField(null=True),
        ),
    ]
