# Generated by Django 3.2.4 on 2021-07-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20210703_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='class_fk_id',
            new_name='class_fk',
        ),
    ]
