# Generated by Django 3.2.4 on 2021-07-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_rename_class_fk_id_member_class_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_num', models.IntegerField(null=True)),
                ('member_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.member')),
                ('studentlist_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.student_list')),
            ],
        ),
    ]
